insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (1,1,'Informática','Computer Science','UNITO', 'Italiano', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (2,1,'Ingeniería','Ingeniería Mecánica','POlITO', 'Italiano', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (3,2,'Matemáticas','Matemáticas','UCC', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (4,2,'Historia','Computer Science','UCC', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (5,3,'Economía','ADE','Universität Wien', 'Alemán', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (6,3,'Matemáticas','Matemáticas','Universität Wien', 'Alemán', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (7,4,'Historia','Historia de Artes','Universität der Künste Berlín', 'Alemán', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (8,4,'Filología','Filología Alemana','Freie Universität Berlin', 'Alemán', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (9,5,'Ciencias sociales','Trabajo Social','Unizar', 'Español', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (10,5,'Ciencias de la salud','Medicina','Unizar', 'Español', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (11,6,'Derecho','Derecho','Aalborg University', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (12,6,'Física','Física','Aalborg University', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (13,7,'Geografía','Geografía','Université de Nantes', 'Francés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (14,7,'Química','Química','Université de Nantes', 'Francés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (15,8,'Veterinaria','Veterinaria','University of Oslo', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (16,8,'Matemáticas','Matemáticas','University of Oslo', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (17,9,'Historia','Historia del Arte','Oxford University', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (18,9,'Informática','Ingeniería Informática','Oxford University', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (19,10,'Matemáticas','Matemáticas','University of Borås', 'Inglés', NULL, TRUE);
insert into erasmus.Carrera (idCarrera, destino, rama, carrera, universidad, idioma, imagen, validado) values (20,10,'Historia','Historia ','University of Borås', 'Inglés', NULL, TRUE);