INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (1,'Bibendum Sed LLP',2,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (10,'Arcu Vestibulum Ante Industries',9,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (9,'Curabitur Massa Vestibulum Industries',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (2,'Ornare Tortor Corp.',2,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (10,'Ante Iaculis Nec Limited',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (10,'Aliquam Enim PC',9,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (10,'Nullam Incorporated',8,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (10,'Nunc Mauris Elit Consulting',2,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Magna Nec Quam Corp.',12,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (15,'Sapien Nunc Ltd',4,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (17,'Justo Sit Amet Inc.',8,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (4,'Elementum At Corp.',10,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (14,'Mi Enim Consulting',10,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Cursus Integer Mollis Institute',9,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (7,'Eu Company',3,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'In At Pede Inc.',4,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (6,'Nulla Facilisis Suspendisse Limited',11,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Nec Cursus Corp.',10,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (9,'Auctor Inc.',9,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (7,'Sed Facilisis Vitae Corporation',6,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (12,'Diam Sed Diam Corp.',2,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Pede Incorporated',12,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Donec Non Justo Limited',8,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (12,'Pede Institute',2,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (15,'Vitae Mauris Incorporated',5,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (14,'Ipsum Ac Mi Inc.',11,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (15,'Lacus Varius Et Associates',4,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (15,'Laoreet Inc.',7,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (8,'Velit PC',4,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (3,'Nisi Mauris Corp.',7,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (19,'A Neque Nullam LLC',4,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Quis Pede Suspendisse Limited',11,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (14,'Quis Incorporated',6,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (9,'Diam Lorem Auctor Foundation',12,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (6,'Nulla Dignissim Maecenas Consulting',12,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (18,'Nullam Feugiat Institute',8,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (15,'Ut Erat Limited',10,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (16,'Risus At Fringilla Foundation',2,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Donec Limited',11,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (16,'Magna Corporation',12,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (6,'Et Associates',12,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (9,'Odio Semper Foundation',12,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Lobortis Augue LLP',2,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (9,'Ac Orci Corporation',10,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (20,'Blandit Enim Consequat Industries',7,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (9,'Pellentesque Ultricies Dignissim LLC',3,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (14,'Aliquam LLC',2,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (8,'Ullamcorper Velit In PC',12,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (20,'Donec Vitae PC',7,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (6,'Viverra LLP',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (12,'Posuere LLC',8,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (1,'Eu Incorporated',9,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Aliquam Arcu Aliquam Limited',11,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (7,'In Corporation',12,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (12,'Sem Pellentesque Ut Corp.',4,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (8,'Interdum Feugiat Sed Institute',4,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (17,'Elit Limited',2,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (4,'Suspendisse PC',11,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Ante Blandit Viverra Corporation',7,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (20,'In Consectetuer Ipsum Company',7,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Nunc Interdum Feugiat Institute',8,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (14,'A Magna Lorem LLP',6,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (17,'Donec Consectetuer Corporation',3,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (7,'Cras Ltd',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Erat Corp.',11,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Vitae Industries',5,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Eu Nibh Corporation',10,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Gravida Limited',2,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (16,'Tempus Eu LLC',11,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (6,'Erat Etiam Vestibulum Limited',12,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Et Incorporated',7,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (14,'Nonummy Inc.',12,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (20,'Quam Elementum Foundation',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (15,'Molestie Corp.',2,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (2,'Ipsum LLP',5,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (14,'Penatibus Et Corp.',12,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (10,'Ut Quam Vel Industries',5,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (19,'Donec Tempor Est Ltd',3,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Odio Etiam Ligula Corporation',7,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (7,'Mattis LLP',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (2,'Metus Urna Industries',9,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (10,'Sed Foundation',11,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (20,'In Lobortis Tellus Consulting',7,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (2,'Aliquam Associates',9,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (9,'Eros Associates',5,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (1,'Id Enim Limited',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (6,'Velit Egestas Industries',10,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (2,'Etiam Laoreet Libero Inc.',10,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (14,'A Ultricies Adipiscing LLC',4,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (3,'Eros Nam Consequat Ltd',9,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (13,'Consequat Purus Maecenas Corp.',9,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (18,'A Aliquet Vel PC',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (4,'Dictum Placerat Corp.',10,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (5,'Suspendisse Associates',11,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (3,'Ac Orci Foundation',3,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (20,'Convallis Foundation',3,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (10,'Eu Consulting',11,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (4,'Aliquam Fringilla Cursus Institute',12,1,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (11,'Justo Incorporated',11,2,TRUE);
INSERT INTO Asignaturas (Carrera,Nombre,Creditos,Cuatrimestre,Validado) VALUES (4,'Ultrices Vivamus Company',2,2,TRUE);

