-- MySQL Script generated by MySQL Workbench
-- 03/20/16 21:33:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Erasmus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Erasmus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Erasmus` DEFAULT CHARACTER SET utf8 ;
USE `Erasmus` ;

-- -----------------------------------------------------
-- Table `Erasmus`.`Destinos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erasmus`.`Destinos` ;

CREATE TABLE IF NOT EXISTS `Erasmus`.`Destinos` (
  `idDestino` INT NOT NULL,
  `Pais` TEXT NOT NULL,
  `Ciudad` TEXT NOT NULL,
  `Validado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idDestino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Erasmus`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erasmus`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Erasmus`.`Usuarios` (
  `Correo` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Erasmus`.`Comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erasmus`.`Comentarios` ;

CREATE TABLE IF NOT EXISTS `Erasmus`.`Comentarios` (
  `idComentario` INT NOT NULL,
  `Destino` INT NOT NULL,
  `Usuario` VARCHAR(50) NOT NULL,
  `Comentario` TEXT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `Destino_idx` (`Destino` ASC),
  INDEX `Usuario_idx` (`Usuario` ASC),
  CONSTRAINT `Destino_C`
    FOREIGN KEY (`Destino`)
    REFERENCES `Erasmus`.`Destinos` (`idDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuario_C`
    FOREIGN KEY (`Usuario`)
    REFERENCES `Erasmus`.`Usuarios` (`Correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Erasmus`.`Valoraciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erasmus`.`Valoraciones` ;

CREATE TABLE IF NOT EXISTS `Erasmus`.`Valoraciones` (
  `idValoracion` INT NOT NULL,
  `Usuario` VARCHAR(50) NOT NULL,
  `Destino` INT NOT NULL,
  `Valoracion` INT NOT NULL,
  PRIMARY KEY (`idValoracion`),
  INDEX `Usuario_idx` (`Usuario` ASC),
  INDEX `Destino_idx` (`Destino` ASC),
  CONSTRAINT `Usuario_V`
    FOREIGN KEY (`Usuario`)
    REFERENCES `Erasmus`.`Usuarios` (`Correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Destino_V`
    FOREIGN KEY (`Destino`)
    REFERENCES `Erasmus`.`Destinos` (`idDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Erasmus`.`Rama`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erasmus`.`Rama` ;

CREATE TABLE IF NOT EXISTS `Erasmus`.`Rama` (
  `idRama` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRama`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Erasmus`.`Carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erasmus`.`Carrera` ;

CREATE TABLE IF NOT EXISTS `Erasmus`.`Carrera` (
  `idCarrera` INT NOT NULL,
  `Destino` INT NOT NULL,
  `Rama` VARCHAR(100) NOT NULL,
  `Carrera` TEXT NOT NULL,
  `Universidad` TEXT NOT NULL,
  `Idioma` TEXT NOT NULL,
  `Imagen` TEXT NULL,
  `Validado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idCarrera`),
  INDEX `Destino_idx` (`Destino` ASC),
  INDEX `Rama_idx` (`Rama` ASC),
  CONSTRAINT `Destino_Car`
    FOREIGN KEY (`Destino`)
    REFERENCES `Erasmus`.`Destinos` (`idDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Rama_Car`
    FOREIGN KEY (`Rama`)
    REFERENCES `Erasmus`.`Rama` (`idRama`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Erasmus`.`Asignaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erasmus`.`Asignaturas` ;

CREATE TABLE IF NOT EXISTS `Erasmus`.`Asignaturas` (
  `idAsignatura` INT NOT NULL,
  `Carrera` INT NOT NULL,
  `Nombre` TEXT NOT NULL,
  `Validado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idAsignatura`),
  INDEX `idCarrera_idx` (`Carrera` ASC),
  CONSTRAINT `idCarrera_A`
    FOREIGN KEY (`Carrera`)
    REFERENCES `Erasmus`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Erasmus`.`Valoraciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erasmus`.`Valoraciones` ;

CREATE TABLE IF NOT EXISTS `Erasmus`.`Valoraciones` (
  `idValoracion` INT NOT NULL,
  `Usuario` VARCHAR(50) NOT NULL,
  `Destino` INT NOT NULL,
  `Valoracion` INT NOT NULL,
  PRIMARY KEY (`idValoracion`),
  INDEX `Usuario_idx` (`Usuario` ASC),
  INDEX `Destino_idx` (`Destino` ASC),
  CONSTRAINT `Usuario_V`
    FOREIGN KEY (`Usuario`)
    REFERENCES `Erasmus`.`Usuarios` (`Correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Destino_V`
    FOREIGN KEY (`Destino`)
    REFERENCES `Erasmus`.`Destinos` (`idDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
