insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (1,'Italia','Turin',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (2,'Irlanda','Cork',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (3,'Austria','Viena',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (4,'Alemania','Berlin',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (5,'España','Zaragoza',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (6,'Dinamarca','Aalborg',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (7,'Francia','Nantes',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (8,'Noruega','Oslo',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (9,'Reino Unido','Oxford',TRUE);
insert into erasmus.Destinos (idDestino, Pais, Ciudad, Validado) values (10,'Suecia','Boras',TRUE);