insert into Rama(idrama) values ('Biología');
insert into Rama(idrama) values ('Ciencias sociales');
insert into Rama(idrama) values ('Ciencias de la salud');
insert into Rama(idrama) values ('Derecho');
insert into Rama(idrama) values ('Economía');
insert into Rama(idrama) values ('Filología');
insert into Rama(idrama) values ('Física');
insert into Rama(idrama) values ('Geografía');
insert into Rama(idrama) values ('Historia');
insert into Rama(idrama) values ('Informática');
insert into Rama(idrama) values ('Ingenieria');
insert into Rama(idrama) values ('Matemáticas');
insert into Rama(idrama) values ('Química');
insert into Rama(idrama) values ('Veterinaria');
